### PR TITLE
Add task completion column to issues table and in progress epics

### PR DESCRIPTION
**Pull request by aaronyzhou**
image

### CODE REVIEW

**Review by jclem — APPROVED** [review]
Feature-wise I don't feel I should be reviewing this project much right now, but as long as everything CI-wise passes it's good by me.

**Comment by scottdensmore** [comment]
@aaronyzhou if folks don't track tasks for a feature what will they see?

**Comment by aaronyzhou** [comment]
> @aaronyzhou if folks don't track tasks for a feature what will they see?

It will just say 0/0 without a progress bar

**Review by scottdensmore — APPROVED** [review]

**Comment by scottdensmore** [comment]
@aloviedo Are you good with this?

**Comment by scottdensmore** [comment]
@aloviedo You good if we merge this? If we don't here any objections, I will next week.

**Pull request merged**
